# Generated by Django 4.0.2 on 2022-02-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sequence'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='software',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
