# Generated by Django 4.0.2 on 2022-02-24 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_category_options_alter_developer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
