# Generated by Django 4.0.2 on 2022-06-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_software_free'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sequence', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['name'], 'verbose_name_plural': 'Software'},
        ),
    ]
