# Generated by Django 4.0.2 on 2022-06-17 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_alter_category_options_alter_software_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 3, 38, 12, 880047)),
        ),
    ]
